-- MySQL Script generated by MySQL Workbench
-- Tue Nov  7 13:48:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hci-restaurant
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hci-restaurant
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hci-restaurant` DEFAULT CHARACTER SET utf8 ;
USE `hci-restaurant` ;

-- -----------------------------------------------------
-- Table `hci-restaurant`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hci-restaurant`.`Role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hci-restaurant`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hci-restaurant`.`User` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `salary` VARCHAR(45) NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`username`),
  INDEX `fk_User_Role_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_Role`
    FOREIGN KEY (`role_id`)
    REFERENCES `hci-restaurant`.`Role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hci-restaurant`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hci-restaurant`.`Status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hci-restaurant`.`Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hci-restaurant`.`Table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `seats_number` INT NOT NULL,
  `is_busy` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hci-restaurant`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hci-restaurant`.`Order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` DATETIME NOT NULL,
  `note` VARCHAR(200) NULL,
  `status_id` INT NOT NULL,
  `table_id` INT NOT NULL,
  `user_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Order_Status1_idx` (`status_id` ASC) VISIBLE,
  INDEX `fk_Order_Table1_idx` (`table_id` ASC) VISIBLE,
  INDEX `fk_Order_User1_idx` (`user_username` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `hci-restaurant`.`Status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Table1`
    FOREIGN KEY (`table_id`)
    REFERENCES `hci-restaurant`.`Table` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_User1`
    FOREIGN KEY (`user_username`)
    REFERENCES `hci-restaurant`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hci-restaurant`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hci-restaurant`.`Category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hci-restaurant`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hci-restaurant`.`Item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `price` DECIMAL(5,2) NOT NULL,
  `description` VARCHAR(200) NULL,
  `is_available` TINYINT NOT NULL,
  `photo` VARCHAR(255) NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Item_Category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_Item_Category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `hci-restaurant`.`Category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hci-restaurant`.`Dish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hci-restaurant`.`Dish` (
  `is_vegan` TINYINT NOT NULL,
  `item_id` INT NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_Dish_Item1_idx` (`item_id` ASC) VISIBLE,
  CONSTRAINT `fk_Dish_Item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `hci-restaurant`.`Item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hci-restaurant`.`Drink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hci-restaurant`.`Drink` (
  `is_alcoholic` TINYINT NOT NULL,
  `item_id` INT NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_Drink_Item1_idx` (`item_id` ASC) VISIBLE,
  CONSTRAINT `fk_Drink_Item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `hci-restaurant`.`Item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hci-restaurant`.`Receipt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hci-restaurant`.`Receipt` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Receipt_User1_idx` (`user_username` ASC) VISIBLE,
  CONSTRAINT `fk_Receipt_User1`
    FOREIGN KEY (`user_username`)
    REFERENCES `hci-restaurant`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hci-restaurant`.`Order_has_Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hci-restaurant`.`Order_has_Item` (
  `order_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`order_id`, `item_id`),
  INDEX `fk_Order_has_Item_Item1_idx` (`item_id` ASC) VISIBLE,
  INDEX `fk_Order_has_Item_Order1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_has_Item_Order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `hci-restaurant`.`Order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_has_Item_Item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `hci-restaurant`.`Item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hci-restaurant`.`Receipt_has_Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hci-restaurant`.`Receipt_has_Item` (
  `receipt_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`receipt_id`, `item_id`),
  INDEX `fk_Receipt_has_Item_Item1_idx` (`item_id` ASC) VISIBLE,
  INDEX `fk_Receipt_has_Item_Receipt1_idx` (`receipt_id` ASC) VISIBLE,
  CONSTRAINT `fk_Receipt_has_Item_Receipt1`
    FOREIGN KEY (`receipt_id`)
    REFERENCES `hci-restaurant`.`Receipt` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Receipt_has_Item_Item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `hci-restaurant`.`Item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hci-restaurant`.`Settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hci-restaurant`.`Settings` (
  `user_username` VARCHAR(45) NOT NULL,
  `theme` VARCHAR(45) NOT NULL,
  `language` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_username`),
  CONSTRAINT `fk_Settings_User1`
    FOREIGN KEY (`user_username`)
    REFERENCES `hci-restaurant`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
